// aprendiendovue/src/components/BlogComponent.vue
<template>
  <div>
    <SliderComponent texto="Blog"></SliderComponent>
    <div class="center">
      <section id="content">
        <h2 class="subheader">Blog</h2>
        <div id="articles">
          <article class="article-item" v-for="article in articles" :key="article._id">
            <div class="image-wrap">
              <img
                :src="url+'get-image/'+article.image"
                alt="imagen estrellas"
                v-if="article.image"
              />
              <img src="../assets/image/no-image.jpg" alt="imagen estrellas" v-if="!article.image" />
            </div>
            <h2>{{article.title}}</h2>

            <span class="date">{{article.date}}</span>
            <router-link to="'/blog/article'+article._id">leer mas</router-link>
            <div class="clearfix"></div>
          </article>
          <!-- agegan lo otros articulos -->
        </div>
      </section>
      <SidebarComponent></SidebarComponent>
    </div>
  </div>
</template>

<script>
import axios from "axios";
import SidebarComponent from "./SidebarComponent.vue";
import SliderComponent from "./SliderComponent.vue";
export default {
  name: "BlogComponent",
  components: {
    SliderComponent,
    SidebarComponent
  },
  data() {
    return {
      articles: [],
      url: "http://localhost:8080/api/",
      keyarticle: 0
    };
  },
  mounted() {
    this.getArticle();
  },
  computed: {},
  methods: {
    getArticle() {
      axios
        .get(this.url + "articles")
        .then(res => {
          console.log(res.data.article);
          this.articles = res.data.article;
        })
        .catch(err => console.log(err));
    }
  }
};
</script>

<style></style>

// AprendiendoAngular/src/app/components/blog/blog.component.ts
import { Component, OnInit } from "@angular/core";
import { ArticuleService } from "src/app/services/article.service";

@Component({
  selector: "app-blog",
  templateUrl: "./blog.component.html",
  styleUrls: ["./blog.component.scss"],
  providers: [ArticuleService],
})
export class BlogComponent implements OnInit {
  titulo: string;
  constructor(private _articleSertvice: ArticuleService) {
    this.titulo = " titulo del blog";
  }

  ngOnInit(): void {
    // console.log(this._articleSertvice.pruebas());
    this._articleSertvice.getArticles().subscribe(
      (res) => {
        console.log(res);
      },
      (err) => {
        console.log(err);
      }
    );
  }
}

<app-slider [nombre]="'blog'" [size]="'small'"></app-slider>
<div class="center">
  <section id="content">
    <h2 class="subheader">{{titulo}}</h2>

    <div class="article">
      <article class="article-item" *ngFor="let article of articles">
        <div class="image-wrap"><img src="{{url + 'get-image/' +article.image}}" alt="imagen estrellas"
            *ngIf=article.image>
          <img src="assets/images/noImage.jpg" alt="imagen estrellas" *ngIf=!article.image>
        </div>
        <h2>{{article.title}}</h2>

        <span class="date">{{article.date}}</span>
        <a href="#">leer mas</a>
        <div class="clearfix"></div>
      </article>
    </div>

  </section>

  <app-sidebar></app-sidebar>
</div>
