// AprendiendoAngular/src/app/components/article/article.component.ts
import { Component, OnInit } from "@angular/core";
import { ArticleService } from "src/app/services/article.service";
import { Article } from "src/app/models/article";
import { Router, ActivatedRoute, Params } from "@angular/router";
import globalVar from "src/app/services/global";

@Component({
  selector: "app-article",
  templateUrl: "./article.component.html",
  styleUrls: ["./article.component.scss"],
  providers: [ArticleService],
})
export class ArticleComponent implements OnInit {
  public title: string;
  public article: Article;
  public url: string;
  constructor(
    private _articleService: ArticleService,
    private _route: ActivatedRoute,
    private _router: Router
  ) {
    this.title = "titulo";
    this.url = globalVar.url;
  }

  ngOnInit(): void {
    this._route.params.subscribe((params: Params) => {
      const id = params["id"];
      this._articleService.getArticle(id).subscribe(
        (res) => {
          if (res.article) {
            this.article = res.article;
            console.log(this.article);
          } else {
            this._router.navigate(["/home"]);
          }
        },
        (err) => {
          console.log(err);
        }
      );
    });
  }
  borrarArticle(id) {
    this._articleService.delete(id).subscribe(
      (res) => {
        console.log(res);
        if (res.msg) {
          alert(" Articulo Borrado Correctamente");
          this._router.navigate(["/blog"]);
        }
      },
      (err) => {
        console.log(err);
      }
    );
  }
}

<div class="center">
  <section id="content">
    <!-- <app-articles [articles]="articles"></app-articles> -->
    <div class="loading" *ngIf="!article"> Cargando ....</div>
    <article class="article-item-detail" id="article-template" *ngIf="article">
      <div class="image-wrap">
        <img src="{{url+'get-image/'+article.image}}" alt="imagen estrellas" *ngIf="article.image">
        <img src="assets/images/noImage.jpg" alt="no hay imagen disponible" *ngIf="!article.image">
      </div>
      <h1 class="subheader">{{article.title}}</h1>

      <span class="date">{{article.date|amLocale : 'es'|amTimeAgo}}</span>
      <div class="clearfix"></div>
      <p>
        {{article.content}}</p>
    </article>
    <div class="buttons">
      <a [routerLink]="['/blog/editar/'+article._id]" class="btn btn-warning">Editar</a>
      <a (click)="borrarArticle(article._id)" class="btn btn-danger">Borrar</a>
    </div>
  </section>

  <app-sidebar></app-sidebar>
</div>

// aprendiendovue/src/components/ArticleComponent.vue
<template>
  <div id="articles">
    <div v-if="!articles">...Cargando</div>

    <article class="article-item" v-for="article in articles" :key="article._id">
      <div class="image-wrap">
        <img :src="url+'get-image/'+article.image" alt="imagen estrellas" v-if="article.image" />
        <img src="../assets/image/no-image.jpg" alt="imagen estrellas" v-if="!article.image" />
      </div>
      <h2>
        <router-link :to="'/blog/articulo/'+article._id">{{article.title}}</router-link>
      </h2>
      <span class="date">{{article.date | moment('from','now') }}</span>
      <router-link :to="'/blog/articulo/'+article._id">leer mas</router-link>
      <div class="clearfix"></div>
    </article>

    <div v-if="articles && articles.length===0">No hay articulos para mostart</div>
  </div>
</template> 

<script>
import Global from "../Global";
export default {
  name: "ArticleComponent",
  props: ["articles"],
  data() {
    return {
      url: Global.url
    };
  }
};
</script>

<style>
</style>
