// AprendiendoAngular/src/app/components/pelicula/pelicula.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from "@angular/core";
import Pelicula from "src/app/models/pelicula";

@Component({
  selector: "app-pelicula",
  templateUrl: "./pelicula.component.html",
  styleUrls: ["./pelicula.component.scss"],
})
export class PeliculaComponent implements OnInit {
  @Input() pelicula: Pelicula;
  @Input() i: number;
  @Output() MarcarFavorita = new EventEmitter();
  constructor() {}

  ngOnInit(): void {}

  selecionarFavorita(e, p) {
    // console.log({ e, p });
    this.MarcarFavorita.emit({ pelicula: p });
  }
}

<article class="article-item">
  <div class="image-wrap">
    <img src={{pelicula.img}} alt={{pelicula.title}}>
  </div>
  <h2>{{i}}_{{pelicula.title}}</h2>
  <span class="date">Hace 5 minutos </span>
  <!-- ngStyle -->
  <!-- <span class="year" [style.background]="pelicula.year > 2016?'green':'red'"> -->
  <!-- <span class="year" [class.year-green]="pelicula.year > 2016" [class.year-red]="pelicula.year <= 2016"> -->
  <!-- <span class="year" [class]="pelicula.year > 2016 ? 'year-green':'year-red'"> -->
  <span class="year" [ngClass]="{
          'year-green': pelicula.year > 2016,
          'year-red': pelicula.year <= 2016
        }">
    {{pelicula.year}}
  </span>
  <a href="#">leer mas</a>
  <button (click)="selecionarFavorita($event,pelicula)"> selecionar como favorita</button>
  <div class="clearfix"></div>
</article>

// aprendiendovue/src/components/PeliculaComponent.vue
<template>
  <article class="article-item">
    <div class="image-wrap">
      <img :src="pelicula.img" alt="imagen estrellas" />
    </div>
    <h2>{{pelicula.title}}</h2>

    <span
      class="date"
      v-bind:class="{
          yeargreen:pelicula.year > 2018,
          yearred:pelicula.year <= 2018
        }
        "
    >{{pelicula.year}}</span>
    <a href="#">leer mas</a>
    <input type="button" value="Favorita" @click="SelecionarFavorita(pelicula)" />
    <div class="clearfix"></div>
  </article>
</template>

<script>
export default {
  name: "peliculaComponent",
  props: ["pelicula"],
  methods: {
    SelecionarFavorita(p) {
      console.log(p);
      this.$emit("favorita", p);
    }
  }
};
</script>

<style>
</style>
