// AprendiendoAngular/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from "@angular/core";
import { Router } from "@angular/router";

@Component({
  selector: "app-sidebar",
  templateUrl: "./sidebar.component.html",
  styleUrls: ["./sidebar.component.scss"],
})
export class SidebarComponent implements OnInit {
  public search: string;
  private url: string;
  constructor(private _router: Router) {}

  ngOnInit(): void {}

  goSearch() {
    // this._router.navigate(["/buscar/" + this.search]);

    this._router.navigate(["/buscar", this.search]);
  }
}

<aside id="sidebar">
  <div class="sidebat-item" id="nav-blog">
    <h3>Puedes hacer esto </h3>
    <a href="#" class="btn btn-success">crear articulo</a>
  </div>
  <div class="sidebat-item" id="search">
    <h3>Puedes hacer esto </h3>
    <p>encuentra el articulo que buscas</p>
    <form #searchform="ngForm" (ngSubmit)="goSearch()">
      <input type="text" name="search" [(ngModel)]="search">
      <input type="submit" name="submit" value="buscar" class="btn">
    </form>
  </div>
</aside>

// aprendiendovue/src/components/SidebarComponent.vue
<template>
  <aside id="sidebar">
    <div class="sidebat-item" id="nav-blog">
      <h3>Puedes hacer esto</h3>
      <a href="#" class="btn btn-success">crear articulo</a>
    </div>
    <div class="sidebat-item" id="search">
      <h3>Puedes hacer esto</h3>
      <p>encuentra el articulo que buscas</p>
      <form action="#">
        <input type="text" name="search" />
        <input type="submit" name="submit" value="buscar" class="btn" />
      </form>
    </div>
  </aside>
</template>

<script>
export default {
  name: "SidebarComponent"
};
</script>

<style>
</style>
